package io.quarkmind.domain;

public enum BuildingType {
    // Protoss
    NEXUS, PYLON, GATEWAY, CYBERNETICS_CORE, ASSIMILATOR,
    ROBOTICS_FACILITY, STARGATE, FORGE, TWILIGHT_COUNCIL,
    PHOTON_CANNON, SHIELD_BATTERY, DARK_SHRINE, TEMPLAR_ARCHIVES,
    FLEET_BEACON, ROBOTICS_BAY,
    // Terran
    COMMAND_CENTER, ORBITAL_COMMAND, PLANETARY_FORTRESS,
    SUPPLY_DEPOT, BARRACKS, ENGINEERING_BAY, ARMORY,
    MISSILE_TURRET, BUNKER, SENSOR_TOWER, GHOST_ACADEMY,
    FACTORY, STARPORT, FUSION_CORE, REFINERY,
    // Zerg
    HATCHERY, LAIR, HIVE, SPAWNING_POOL, EVOLUTION_CHAMBER,
    ROACH_WARREN, BANELING_NEST, SPINE_CRAWLER, SPORE_CRAWLER,
    HYDRALISK_DEN, LURKER_DEN, INFESTATION_PIT, SPIRE, GREATER_SPIRE,
    NYDUS_NETWORK, NYDUS_CANAL, ULTRALISK_CAVERN, EXTRACTOR,
    UNKNOWN
}
