package io.quarkmind.domain;

public enum UnitType {
    // Protoss
    PROBE, ZEALOT, STALKER, IMMORTAL, COLOSSUS, CARRIER,
    DARK_TEMPLAR, HIGH_TEMPLAR, ARCHON, OBSERVER, VOID_RAY,
    ADEPT, DISRUPTOR, SENTRY,
    // Zerg
    ZERGLING, ROACH, HYDRALISK, MUTALISK, ULTRALISK,
    BROOD_LORD, CORRUPTOR, INFESTOR, SWARM_HOST, VIPER, QUEEN, RAVAGER, LURKER,
    // Terran
    MARINE, MARAUDER, MEDIVAC, SIEGE_TANK, THOR, VIKING,
    GHOST, RAVEN, BANSHEE, BATTLECRUISER, CYCLONE, LIBERATOR, WIDOW_MINE,
    // Fallback
    UNKNOWN
}
