package io.quarkmind.domain;

public enum UnitType {
    // Protoss
    PROBE, ZEALOT, STALKER, IMMORTAL, COLOSSUS, CARRIER,
    DARK_TEMPLAR, HIGH_TEMPLAR, ARCHON, OBSERVER, VOID_RAY,
    ADEPT, DISRUPTOR, SENTRY,
    PHOENIX, ORACLE, TEMPEST, MOTHERSHIP,
    WARP_PRISM, WARP_PRISM_PHASING,
    INTERCEPTOR, ADEPT_PHASE_SHIFT,
    // Zerg
    ZERGLING, ROACH, HYDRALISK, MUTALISK, ULTRALISK,
    BROOD_LORD, CORRUPTOR, INFESTOR, SWARM_HOST, VIPER, QUEEN, RAVAGER, LURKER,
    DRONE, OVERLORD, OVERSEER, BANELING,
    LOCUST, BROODLING, INFESTED_TERRAN, CHANGELING,
    // Terran
    MARINE, MARAUDER, MEDIVAC, SIEGE_TANK, SIEGE_TANK_SIEGED, THOR, VIKING,
    GHOST, RAVEN, BANSHEE, BATTLECRUISER, CYCLONE, LIBERATOR, WIDOW_MINE,
    SCV, REAPER, HELLION, HELLBAT, MULE,
    VIKING_ASSAULT, LIBERATOR_AG, AUTO_TURRET,
    // Fallback
    UNKNOWN
}
